[package]
name = "actix-test"
version = "0.1.0"
authors = ["kanekv <kane.isturm+personal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.5"
futures = "0.1.28"